#!/usr/bin/env python3

import argparse
import itertools
import logging
import re
import shlex
import subprocess
import urllib.parse
from datetime import datetime, timedelta
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, HTTPServer
from string import Template


SYSSTAT_METRICS = [
    {
        # sar -q LOAD
        "title": "System Load",
        "metrics": ["ldavg-5", "ldavg-15"],
        "range": (0, 1),
    },
    {
        # sar -u
        "title": "Processor Statistics",
        "metrics": ["%idle"],
        "range": (0, 100),
    },
    {
        # sar -r
        "title": "Memory Utilization",
        "metrics": ["%memused"],
        "range": (0, 100),
    },
    {
        # sar -m TEMP
        "title": "Power Management Statistics",
        "metrics": ["degC"],
        "range": (0, 100),
    },
    {
        # sar -F MOUNT [--fs=fs_list]
        "title": "Mounted File Systems Statistics",
        "metrics": ["%fsused"],
        "range": (0, 100),
    },
    {
        # sar -d [--dev=dev_list]
        "title": "Block Devices Activity",
        "metrics": ["rkB/s", "wkB/s"],
        "range": (0, None),
    },
    {
        # sar -n DEV [--iface=iface_list]
        "title": "Network Statistics",
        "metrics": ["rxkB/s", "txkB/s"],
        "range": (0, None),
    },
]


def fetch_metrics(destination, days):
    sadf_command = (
        "sadf", "-p", "-U",
        "--",
        "-d", "--dev=vda",
        "-F", "MOUNT", "--fs=/",
        "-m", "TEMP",
        "-n", "DEV", "--iface=eth0",
        "-u",
        "-q", "LOAD",
        "-r",
    )  # fmt: skip
    sep = "---8---"
    input_ = [
        ("echo", sep),
        *[itertools.chain(sadf_command, (f"-{d}",)) for d in range(days, 0, -1)],
        sadf_command,
    ]
    proc = subprocess.run(
        ("ssh", "-T", "-q", destination),
        input="\n".join(map(shlex.join, input_)),
        capture_output=True,
        check=True,
        text=True,
    )
    return proc.stdout[proc.stdout.index(sep) + len(sep) + 1 :]  # skip MOTD


GNUPLOT_SCRIPT = """
set terminal svg size 300,200 font "monospace,11"
set tics font "monospace,9"
set key font "monospace,9"

set datafile separator tab
set xdata time
set timefmt "%s"

set style data fillsteps
set style fill transparent solid 0.5 noborder
set tics scale 0
set grid xtics mxtics ytics

set yrange @YRANGE

set xtics time format "%a" 1 days
set mxtics 2
set xrange @XRANGE

set key outside center top horizontal Left reverse

plot for [metric in METRICS] \
     $DATA \
     using 3:6 \
     if (stringcolumn(5) eq metric) \
     title metric
"""


def render_plot(data, period, metric_names, metric_range):
    xrange = (f"{d.timestamp():.0f}" for d in period)
    yrange = (str(r) if r is not None else "*" for r in metric_range)
    input_ = (
        "\n".join(("$DATA << EOD", data, "EOD")),
        f'METRICS="{" ".join(metric_names)}"',
        f'YRANGE="[{":".join(yrange)}]"',
        f'XRANGE="[{":".join(xrange)}]"',
        GNUPLOT_SCRIPT,
    )
    proc = subprocess.run(
        ("gnuplot",),
        input="\n".join(input_),
        capture_output=True,
        check=True,
        text=True,
    )
    return re.sub(r"<\?xml.*?\?>", "", proc.stdout)  # strip xml declaration


DOCUMENT_TEMPLATE = Template("""
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <title>system activity metrics</title>
        <style>
            body {
                background-color: white;
                font-family: monospace;
                font-size: 11px;
            }

            main {
                display: grid;
                grid-template-columns: repeat(auto-fill, 350px);
                justify-content: center;
            }

            figure {
                margin: 0px 25px;
            }

            .title {
                text-align: center;
            }
        </style>
    </head>
    <body><main>$content</main></body>
</html>
""")

REPORT_TEMPLATE = Template("""
<article>
    <h2 class="title">$hostname</h2>
    <div class="report">$report</div>
</article>
""")

SECTION_TEMPLATE = Template("""
<section>
    <h3 class="title">$title</h3>
    <figure>$plot</figure>
</section>
""")


def render_report(hosts):
    delta = timedelta(days=3)
    content = ""
    for host in hosts:
        report = ""
        data = fetch_metrics(host, delta.days)
        for section in SYSSTAT_METRICS:
            plot = render_plot(
                data,
                period=(datetime.now() - delta, datetime.now()),
                metric_names=section["metrics"],
                metric_range=section["range"],
            )
            report += SECTION_TEMPLATE.substitute(title=section["title"], plot=plot)
        content += REPORT_TEMPLATE.substitute(
            hostname=extract_hostname(host),
            report=report,
        )
    return DOCUMENT_TEMPLATE.substitute(content=content)


def extract_hostname(url):
    hostname = urllib.parse.urlsplit(url).hostname
    if not hostname:
        hostname = urllib.parse.urlsplit(f"ssh://{url}").hostname
    if not hostname:
        hostname = url
    return hostname


class Handler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        if self._debug:
            super().log_message(format, *args)

    def do_GET(self):
        match = re.fullmatch(r"/(\d*)", self.path)
        if not match:
            self.send_response(HTTPStatus.NOT_FOUND)
            self.end_headers()
            return

        days_ago = int(match.group(1) or "0")
        try:
            body = render_report().encode()
        except Exception as exc:
            self.log_error("%s", exc)
            self.send_response(HTTPStatus.INTERNAL_SERVER_ERROR)
            self.end_headers()
            return

        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def render(args):
    report = render_report(args.host)
    print(report)


def serve(args):
    httpd = HTTPServer((args.host, args.port), Handler)
    httpd.serve_forever()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="sysstat metrics renderer")

    shared_parser = argparse.ArgumentParser(add_help=False)
    shared_parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="display more information",
    )

    subparsers = parser.add_subparsers(title="subcommands", required=True)

    render_parser = subparsers.add_parser(
        "render",
        help="render once",
        parents=[shared_parser],
    )
    render_parser.add_argument(
        "host",
        help="hostname to fetch metrics from",
        nargs="+",
    )
    render_parser.set_defaults(func=render)

    serve_parser = subparsers.add_parser(
        "serve",
        help="run server",
        parents=[shared_parser],
    )
    serve_parser.add_argument(
        "-H",
        "--host",
        default="localhost",
        help="host to bind to (default: %(default)s)",
    )
    serve_parser.add_argument(
        "-p",
        "--port",
        type=int,
        default=8000,
        help="port to bind to (default: %(default)s)",
    )
    serve_parser.set_defaults(func=serve)

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.ERROR,
        format="%(message)s",
    )

    args.func(args)
